# This is a basic workflow to help you get started with Actions

name: zig fmt check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: fetch zig
        run: curl -o zig.tar.xz https://ziglang.org/builds/zig-linux-x86-0.14.0-dev.2254+73f2671c7.tar.xz

      - name: unpack
        run: mkdir gh-zig && tar xf zig.tar.xz -C gh-zig --strip-components 1

      - name: validate formatting
        run: ./gh-zig/zig fmt --check src
