# This is a basic workflow to help you get started with Actions

name: Zig CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  zig:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install VulkanSDK
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list http://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt update
          sudo apt install vulkan-sdk -y

      - name: Fetch & unpack zig
        run: |
          curl -Ls https://github.com/ft-mojang/zig/releases/download/dev.3258%2Bd2e70ef84/zig-linux-x86_64-0.14.0-dev.3258+d2e70ef84.tar.xz -o zig.tar.xz
          mkdir -p gh-zig && tar xf zig.tar.xz -C gh-zig --strip-components 1
# curl -s  https://ziglang.org/download/index.json | jq '.master."x86_64-linux".tarball' | xargs curl -o zig.tar.xz

      - name: Validate formatting
        run: ./gh-zig/zig fmt --check src

      - name: Build ft_minecraft
        run: |
          ./gh-zig/zig build

      - name: Run tests
        run: ./gh-zig/zig build test
